name = "ecocleanpath-headless"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[vars]
WOO_URL = "https://www.ecocleanpath.com/wp-json/wc/v3"
WC_CONSUMER_KEY = "ck_3b095ee80ec4ecd5495b56ce3e9dc4ff5a7e94ae"
WC_CONSUMER_SECRET = "cs_0c1c3a72c0d992fe563e5bf54a7bb72110263ec2"
NEXT_PUBLIC_SITE_URL = "https://www.ecocleanpath.com"